### ISSUE TITLE
@base no longer prepended in local names

### ISSUE THREAD

**Issue by albertmeronyo** [RDFLib/rdflib-jsonld#48]
Hi,

I've noticed that the JSON-LD parser has changed its output w.r.t. prepending the @base URI to local names. The following code used to read [this file](https://gist.github.com/albertmeronyo/a2fff3db14362d539a1d99598476c92b#file-test-csv-metadata-json)

```
from rdflib import Graph

g = Graph()
g.parse('test.csv-metadata.json', format='json-ld')
```

and the resulting graph contained the triple 
```
N86eb3d54036d4bb98a416ec6022be35b http://www.w3.org/ns/csvw#aboutUrl https://iisg.amsterdam/resource/{_row}
```

However this has changed and now the triple is
```
N86eb3d54036d4bb98a416ec6022be35b http://www.w3.org/ns/csvw#aboutUrl {_row}
```

So it seems either this specific property is not expected to be a URI anymore (but a literal instead), or the parser is not prepending @base to URIs.

Could you help me out with this?

Thanks,
Albert

**Comment by niklasl** [comment]
Your example file uses a context which is based on the JSON-LD context at http://www.w3.org/ns/csvw. I guess that the CSVW context used to define `aboutUrl` with `"@type": "@id"`, which has now changed to `"@type": "csvw:uriTemplate"`.

The former was reasonably wrong, since URI Templates are not IRIs, but strings, specifically with the datatype `csvw:uriTemplate`, which are used as templates to *produce* IRIs.

So yes, my assessment is that this specific property is not expected to be a URI anymore.

**Comment by albertmeronyo** [comment]
Hi @niklasl , thanks! This helps a great deal.

Is the JSON-LD context at http://www.w3.org/ns/csvw retrieved by the parser every time, or is this hard-coded into a recent version of rdflib/rdflib-jsonld ? If the latter is the case the easiest for us would be to revert to the latest version that predates this change.

**Comment by albertmeronyo** [comment]
I answer myself: it's dynamically retrieved every time. We'll use a reverted JSON-LD context for the time being while we work on a solution compatible with csvw:uriTemplate 

Thanks again!
